# Generated by Django 4.0 on 2021-12-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Students_no', models.TextField(default=1900727591)),
                ('Reg_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='update',
            name='Paragraph',
            field=models.TextField(max_length=500),
        ),
    ]
