# Generated by Django 4.0 on 2021-12-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmasapp', '0002_student_alter_update_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Paragraphs',
            field=models.TextField(default='about mubs', max_length=500),
        ),
    ]
